// Auto-generated BPC data with quantity aggregation
// Generated by: update_bpc_data_js.py
// BPCs are grouped by type_id, ME, TE, and runs
const BPC_DATA = [
  {
    "typeId": 16239,
    "name": "Cormorant Blueprint",
    "me": 10,
    "te": 20,
    "runs": 2,
    "quantity": 1,
    "category": "Ships",
    "subcategory": "Destroyer"
  }
];