// Auto-generated buyback program data
// Generated: 2026-02-23 18:14 UTC
const BUYBACK_DATA = {
  "items": [
    {
      "typeId": 16272,
      "name": "Heavy Water",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 104.44
    },
    {
      "typeId": 16273,
      "name": "Liquid Ozone",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 90,
      "sellRate": 98,
      "accepted": true,
      "quota": 1000000,
      "avgJitaBuy": 93.82
    },
    {
      "typeId": 16275,
      "name": "Strontium Clathrates",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 98,
      "accepted": true,
      "quota": 0,
      "avgJitaBuy": 3194.95
    },
    {
      "typeId": 17887,
      "name": "Oxygen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 756.37
    },
    {
      "typeId": 17889,
      "name": "Hydrogen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 600.97
    },
    {
      "typeId": 16274,
      "name": "Helium Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 843.92
    },
    {
      "typeId": 17888,
      "name": "Nitrogen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 711.49
    },
    {
      "typeId": 34,
      "name": "Tritanium",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 100000000,
      "avgJitaBuy": 4.02
    },
    {
      "typeId": 35,
      "name": "Pyerite",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": false,
      "quota": 20000000,
      "avgJitaBuy": 17.58
    },
    {
      "typeId": 37,
      "name": "Isogen",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 180.54
    },
    {
      "typeId": 36,
      "name": "Mexallon",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 64.05
    },
    {
      "typeId": 38,
      "name": "Nocxium",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": false,
      "quota": 100000,
      "avgJitaBuy": 647.14
    },
    {
      "typeId": 39,
      "name": "Zydrine",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 949.08
    },
    {
      "typeId": 40,
      "name": "Megacyte",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 2431.51
    },
    {
      "typeId": 11399,
      "name": "Morphite",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 19235.85
    },
    {
      "typeId": 16634,
      "name": "Atmospheric Gases",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 233.88
    },
    {
      "typeId": 16635,
      "name": "Evaporite Deposits",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 284.89
    },
    {
      "typeId": 16633,
      "name": "Hydrocarbons",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 97,
      "accepted": true,
      "quota": 100000,
      "avgJitaBuy": 604.99
    },
    {
      "typeId": 16636,
      "name": "Silicates",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 363.8
    },
    {
      "typeId": 16640,
      "name": "Cobalt",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 698.69
    },
    {
      "typeId": 16639,
      "name": "Scandium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": false,
      "quota": 50000,
      "avgJitaBuy": 469.47
    },
    {
      "typeId": 16637,
      "name": "Tungsten",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 1340.61
    },
    {
      "typeId": 16638,
      "name": "Titanium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 782.8
    },
    {
      "typeId": 16641,
      "name": "Chromium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 5765.76
    },
    {
      "typeId": 16643,
      "name": "Cadmium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 4554.49
    },
    {
      "typeId": 16644,
      "name": "Platinum",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 7562.41
    },
    {
      "typeId": 16642,
      "name": "Vanadium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 1967.34
    },
    {
      "typeId": 16649,
      "name": "Technetium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": false,
      "quota": 12500,
      "avgJitaBuy": 18907.07
    },
    {
      "typeId": 16646,
      "name": "Mercury",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 3869.61
    },
    {
      "typeId": 16647,
      "name": "Caesium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 5443.02
    },
    {
      "typeId": 16648,
      "name": "Hafnium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 8844.9
    },
    {
      "typeId": 16652,
      "name": "Promethium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": false,
      "quota": 6250,
      "avgJitaBuy": 60663.17
    },
    {
      "typeId": 16651,
      "name": "Neodymium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": false,
      "quota": 1000,
      "avgJitaBuy": 64381.46
    },
    {
      "typeId": 16650,
      "name": "Dysprosium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": true,
      "quota": 6250,
      "avgJitaBuy": 57472.68
    },
    {
      "typeId": 16653,
      "name": "Thulium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": true,
      "quota": 6250,
      "avgJitaBuy": 34634.15
    },
    {
      "typeId": 2329,
      "name": "Biocells",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8824.5
    },
    {
      "typeId": 2345,
      "name": "Camera Drones",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 78422.5
    },
    {
      "typeId": 2348,
      "name": "Gel-Matrix Biopaste",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 113875.0
    },
    {
      "typeId": 2349,
      "name": "Supercomputers",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 84205.0
    },
    {
      "typeId": 2351,
      "name": "Smartfab Units",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 68667.5
    },
    {
      "typeId": 2352,
      "name": "Nuclear Reactors",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 86070.0
    },
    {
      "typeId": 2354,
      "name": "Neocoms",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 81175.0
    },
    {
      "typeId": 2360,
      "name": "Industrial Explosives",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 45212.5
    },
    {
      "typeId": 2361,
      "name": "Hermetic Membranes",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 94110.0
    },
    {
      "typeId": 2367,
      "name": "Cryoprotectant Solution",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 112800.0
    },
    {
      "typeId": 2401,
      "name": "Chiral Structures",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 691.17
    },
    {
      "typeId": 2463,
      "name": "Nanites",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8280.25
    },
    {
      "typeId": 2867,
      "name": "Broadcast Node",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1852750.0
    },
    {
      "typeId": 2868,
      "name": "Integrity Response Drones",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 2120000.0
    },
    {
      "typeId": 2869,
      "name": "Nano-Factory",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 974350.0
    },
    {
      "typeId": 2870,
      "name": "Organic Mortar Applicators",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 909075.0
    },
    {
      "typeId": 2871,
      "name": "Recursive Computing Module",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1173250.0
    },
    {
      "typeId": 2872,
      "name": "Self-Harmonizing Power Core",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1898250.0
    },
    {
      "typeId": 2875,
      "name": "Sterile Conduits",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1004500.0
    },
    {
      "typeId": 2876,
      "name": "Wetware Mainframe",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1869250.0
    },
    {
      "typeId": 3645,
      "name": "Water",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 453.75
    },
    {
      "typeId": 3775,
      "name": "Viral Agent",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 11005.0
    },
    {
      "typeId": 3779,
      "name": "Biomass",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 848.35
    },
    {
      "typeId": 3828,
      "name": "Construction Blocks",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 7928.75
    },
    {
      "typeId": 9838,
      "name": "Superconductors",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9971.25
    },
    {
      "typeId": 9842,
      "name": "Miniature Electronics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 11310.0
    },
    {
      "typeId": 9846,
      "name": "Planetary Vehicles",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 112800.0
    },
    {
      "typeId": 44,
      "name": "Enriched Uranium",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10338.0
    },
    {
      "typeId": 3683,
      "name": "Oxygen",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 396.84
    },
    {
      "typeId": 3689,
      "name": "Mechanical Parts",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9819.0
    },
    {
      "typeId": 9832,
      "name": "Coolant",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9485.0
    },
    {
      "typeId": 9848,
      "name": "Robotics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 79088.0
    },
    {
      "typeId": 9830,
      "name": "Rocket Fuel",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10906.0
    },
    {
      "typeId": 9834,
      "name": "Guidance Systems",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 76126.0
    },
    {
      "typeId": 9836,
      "name": "Consumer Electronics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8252.6
    },
    {
      "typeId": 9840,
      "name": "Transmitter",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10216.0
    },
    {
      "typeId": 2312,
      "name": "Supertensile Plastics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 13304.0
    },
    {
      "typeId": 2317,
      "name": "Oxides",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8462.0
    },
    {
      "typeId": 3812,
      "name": "Data Sheets",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 172.6
    },
    {
      "typeId": 25588,
      "name": "Scorched Telemetry Processor",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 2078.44,
      "tier": "Common"
    },
    {
      "typeId": 25589,
      "name": "Malfunctioning Shield Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 348.65,
      "tier": "Common"
    },
    {
      "typeId": 25593,
      "name": "Smashed Trigger Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 8460.56,
      "tier": "Common"
    },
    {
      "typeId": 25595,
      "name": "Alloyed Tritanium Bar",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 2269.0,
      "tier": "Common"
    },
    {
      "typeId": 25596,
      "name": "Broken Drone Transceiver",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 3099.09,
      "tier": "Common"
    },
    {
      "typeId": 25597,
      "name": "Damaged Artificial Neural Network",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 215.01,
      "tier": "Common"
    },
    {
      "typeId": 25598,
      "name": "Tripped Power Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 2521.91,
      "tier": "Common"
    },
    {
      "typeId": 25599,
      "name": "Charred Micro Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 215.2,
      "tier": "Common"
    },
    {
      "typeId": 25590,
      "name": "Contaminated Nanite Compound",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 70423.82,
      "tier": "Uncommon"
    },
    {
      "typeId": 25591,
      "name": "Contaminated Lorentz Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 90246.76,
      "tier": "Uncommon"
    },
    {
      "typeId": 25592,
      "name": "Defective Current Pump",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 11650.0,
      "tier": "Uncommon"
    },
    {
      "typeId": 25594,
      "name": "Tangled Power Conduit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 91877.35,
      "tier": "Uncommon"
    },
    {
      "typeId": 25600,
      "name": "Burned Logic Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 25619.12,
      "tier": "Uncommon"
    },
    {
      "typeId": 25601,
      "name": "Fried Interface Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 2395.71,
      "tier": "Uncommon"
    },
    {
      "typeId": 25602,
      "name": "Thruster Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 11464.41,
      "tier": "Uncommon"
    },
    {
      "typeId": 25603,
      "name": "Melted Capacitor Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 4873.12,
      "tier": "Uncommon"
    },
    {
      "typeId": 25604,
      "name": "Conductive Polymer",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 19016.47,
      "tier": "Uncommon"
    },
    {
      "typeId": 25605,
      "name": "Armor Plates",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 23087.65,
      "tier": "Uncommon"
    },
    {
      "typeId": 25606,
      "name": "Ward Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 14540.88,
      "tier": "Uncommon"
    },
    {
      "typeId": 25607,
      "name": "Telemetry Processor",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 71317.94,
      "tier": "Rare"
    },
    {
      "typeId": 25611,
      "name": "Current Pump",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 50757.06,
      "tier": "Rare"
    },
    {
      "typeId": 25613,
      "name": "Power Conduit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 458579.41,
      "tier": "Rare"
    },
    {
      "typeId": 25614,
      "name": "Single-crystal Superalloy I-beam",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 122982.35,
      "tier": "Rare"
    },
    {
      "typeId": 25615,
      "name": "Drone Transceiver",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 61545.0,
      "tier": "Rare"
    },
    {
      "typeId": 25616,
      "name": "Artificial Neural Network",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 993.56,
      "tier": "Rare"
    },
    {
      "typeId": 25618,
      "name": "Micro Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 3626.59,
      "tier": "Rare"
    },
    {
      "typeId": 25620,
      "name": "Interface Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 7419.41,
      "tier": "Rare"
    },
    {
      "typeId": 25621,
      "name": "Impetus Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 96482.94,
      "tier": "Rare"
    },
    {
      "typeId": 25623,
      "name": "Conductive Thermoplastic",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 21710.0,
      "tier": "Rare"
    },
    {
      "typeId": 25608,
      "name": "Intact Shield Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 462205.88,
      "tier": "Very Rare"
    },
    {
      "typeId": 25609,
      "name": "Nanite Compound",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1280176.47,
      "tier": "Very Rare"
    },
    {
      "typeId": 25610,
      "name": "Lorentz Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 814088.24,
      "tier": "Very Rare"
    },
    {
      "typeId": 25612,
      "name": "Trigger Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1073647.06,
      "tier": "Very Rare"
    },
    {
      "typeId": 25617,
      "name": "Power Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 248467.65,
      "tier": "Very Rare"
    },
    {
      "typeId": 25619,
      "name": "Logic Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1867676.47,
      "tier": "Very Rare"
    },
    {
      "typeId": 25622,
      "name": "Capacitor Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 225164.71,
      "tier": "Very Rare"
    },
    {
      "typeId": 25624,
      "name": "Intact Armor Plates",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 2085058.82,
      "tier": "Very Rare"
    },
    {
      "typeId": 25625,
      "name": "Enhanced Ward Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1192764.71,
      "tier": "Very Rare"
    },
    {
      "typeId": 28361,
      "name": "Drone Synaptic Relay Wiring",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 708.0,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28362,
      "name": "Drone Capillary Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 3932.94,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28363,
      "name": "Drone Cerebral Fragment",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 294035.29,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28364,
      "name": "Drone Tactical Limb",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 3908.71,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28365,
      "name": "Drone Epidermal Shielding Chunk",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 1006.0,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28366,
      "name": "Drone Coronary Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 17879.41,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 21815,
      "name": "Elite Drone AI",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 1982735.29,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 81945,
      "name": "Drone Graviton Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 682955.88,
      "tier": "Rogue Drone"
    }
  ],
  "categories": {
    "minerals": {
      "displayName": "Minerals",
      "visible": true
    },
    "ice_products": {
      "displayName": "Ice Products",
      "visible": true
    },
    "moon_materials": {
      "displayName": "Reaction Materials",
      "visible": true
    },
    "salvaged_materials": {
      "displayName": "Salvaged Materials",
      "visible": true
    }
  },
  "generated": "2026-02-23 18:14 UTC"
};
