// Auto-generated buyback program data
// Generated: 2026-02-27 15:04 UTC
const BUYBACK_DATA = {
  "items": [
    {
      "typeId": 16272,
      "name": "Heavy Water",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 102.22
    },
    {
      "typeId": 16273,
      "name": "Liquid Ozone",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 90,
      "sellRate": 98,
      "accepted": false,
      "quota": 1000000,
      "avgJitaBuy": 90.33
    },
    {
      "typeId": 16275,
      "name": "Strontium Clathrates",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 90,
      "sellRate": 98,
      "accepted": true,
      "quota": 0,
      "avgJitaBuy": 3274.46
    },
    {
      "typeId": 17887,
      "name": "Oxygen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 739.81
    },
    {
      "typeId": 17889,
      "name": "Hydrogen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 560.38
    },
    {
      "typeId": 16274,
      "name": "Helium Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 837.72
    },
    {
      "typeId": 17888,
      "name": "Nitrogen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 90,
      "sellRate": 97,
      "accepted": true,
      "quota": 0,
      "avgJitaBuy": 694.24
    },
    {
      "typeId": 34,
      "name": "Tritanium",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 100000000,
      "avgJitaBuy": 3.97
    },
    {
      "typeId": 35,
      "name": "Pyerite",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": false,
      "quota": 20000000,
      "avgJitaBuy": 17.7
    },
    {
      "typeId": 37,
      "name": "Isogen",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 180.74
    },
    {
      "typeId": 36,
      "name": "Mexallon",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 66.19
    },
    {
      "typeId": 38,
      "name": "Nocxium",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": false,
      "quota": 100000,
      "avgJitaBuy": 659.39
    },
    {
      "typeId": 39,
      "name": "Zydrine",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 943.66
    },
    {
      "typeId": 40,
      "name": "Megacyte",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 2492.04
    },
    {
      "typeId": 11399,
      "name": "Morphite",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": false,
      "quota": 500,
      "avgJitaBuy": 18810.93
    },
    {
      "typeId": 16634,
      "name": "Atmospheric Gases",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 233.19
    },
    {
      "typeId": 16635,
      "name": "Evaporite Deposits",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 290.86
    },
    {
      "typeId": 16633,
      "name": "Hydrocarbons",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 97,
      "accepted": true,
      "quota": 100000,
      "avgJitaBuy": 584.74
    },
    {
      "typeId": 16636,
      "name": "Silicates",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 376.09
    },
    {
      "typeId": 16640,
      "name": "Cobalt",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 561.86
    },
    {
      "typeId": 16639,
      "name": "Scandium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 457.62
    },
    {
      "typeId": 16637,
      "name": "Tungsten",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 1379.33
    },
    {
      "typeId": 16638,
      "name": "Titanium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 762.76
    },
    {
      "typeId": 16641,
      "name": "Chromium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 5462.48
    },
    {
      "typeId": 16643,
      "name": "Cadmium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 4293.56
    },
    {
      "typeId": 16644,
      "name": "Platinum",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 7186.73
    },
    {
      "typeId": 16642,
      "name": "Vanadium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 1943.19
    },
    {
      "typeId": 16649,
      "name": "Technetium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": false,
      "quota": 12500,
      "avgJitaBuy": 18792.31
    },
    {
      "typeId": 16646,
      "name": "Mercury",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 3620.35
    },
    {
      "typeId": 16647,
      "name": "Caesium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 5266.44
    },
    {
      "typeId": 16648,
      "name": "Hafnium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 9081.77
    },
    {
      "typeId": 16652,
      "name": "Promethium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": false,
      "quota": 6250,
      "avgJitaBuy": 61725.77
    },
    {
      "typeId": 16651,
      "name": "Neodymium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": false,
      "quota": 1000,
      "avgJitaBuy": 64681.73
    },
    {
      "typeId": 16650,
      "name": "Dysprosium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": true,
      "quota": 6250,
      "avgJitaBuy": 57228.27
    },
    {
      "typeId": 16653,
      "name": "Thulium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": true,
      "quota": 6250,
      "avgJitaBuy": 33535.58
    },
    {
      "typeId": 2329,
      "name": "Biocells",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8528.86
    },
    {
      "typeId": 2345,
      "name": "Camera Drones",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 80020.91
    },
    {
      "typeId": 2348,
      "name": "Gel-Matrix Biopaste",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 113368.18
    },
    {
      "typeId": 2349,
      "name": "Supercomputers",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 88409.55
    },
    {
      "typeId": 2351,
      "name": "Smartfab Units",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 68812.27
    },
    {
      "typeId": 2352,
      "name": "Nuclear Reactors",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 86270.0
    },
    {
      "typeId": 2354,
      "name": "Neocoms",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 81282.73
    },
    {
      "typeId": 2360,
      "name": "Industrial Explosives",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 47928.18
    },
    {
      "typeId": 2361,
      "name": "Hermetic Membranes",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 94910.91
    },
    {
      "typeId": 2367,
      "name": "Cryoprotectant Solution",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 114436.36
    },
    {
      "typeId": 2401,
      "name": "Chiral Structures",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 670.39
    },
    {
      "typeId": 2463,
      "name": "Nanites",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8395.77
    },
    {
      "typeId": 2867,
      "name": "Broadcast Node",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1861545.45
    },
    {
      "typeId": 2868,
      "name": "Integrity Response Drones",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 2108000.0
    },
    {
      "typeId": 2869,
      "name": "Nano-Factory",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 965604.55
    },
    {
      "typeId": 2870,
      "name": "Organic Mortar Applicators",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 905090.91
    },
    {
      "typeId": 2871,
      "name": "Recursive Computing Module",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1190136.36
    },
    {
      "typeId": 2872,
      "name": "Self-Harmonizing Power Core",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1931090.91
    },
    {
      "typeId": 2875,
      "name": "Sterile Conduits",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1026409.09
    },
    {
      "typeId": 2876,
      "name": "Wetware Mainframe",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1914272.73
    },
    {
      "typeId": 3645,
      "name": "Water",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 445.24
    },
    {
      "typeId": 3775,
      "name": "Viral Agent",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10972.73
    },
    {
      "typeId": 3779,
      "name": "Biomass",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 849.61
    },
    {
      "typeId": 3828,
      "name": "Construction Blocks",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8285.86
    },
    {
      "typeId": 9838,
      "name": "Superconductors",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9732.27
    },
    {
      "typeId": 9842,
      "name": "Miniature Electronics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 11719.55
    },
    {
      "typeId": 9846,
      "name": "Planetary Vehicles",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 113290.91
    },
    {
      "typeId": 2358,
      "name": "Biotech Research Reports",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 86344.12
    },
    {
      "typeId": 2344,
      "name": "Condensates",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 46945.88
    },
    {
      "typeId": 17392,
      "name": "Data Chips",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 88589.41
    },
    {
      "typeId": 2366,
      "name": "Hazmat Detection Systems",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 103258.82
    },
    {
      "typeId": 17898,
      "name": "High-Tech Transmitters",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 84601.18
    },
    {
      "typeId": 2346,
      "name": "Synthetic Synapses",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 77450.0
    },
    {
      "typeId": 12836,
      "name": "Transcranial Microcontrollers",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 68821.18
    },
    {
      "typeId": 17136,
      "name": "Ukomi Superconductors",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 74780.0
    },
    {
      "typeId": 28974,
      "name": "Vaccines",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 70000.0
    },
    {
      "typeId": 15317,
      "name": "Genetically Enhanced Livestock",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 11486.47
    },
    {
      "typeId": 2327,
      "name": "Microfiber Shielding",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 14517.06
    },
    {
      "typeId": 2321,
      "name": "Polyaramids",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 16025.88
    },
    {
      "typeId": 3695,
      "name": "Polytextiles",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 5097.35
    },
    {
      "typeId": 3697,
      "name": "Silicate Glass",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 13262.94
    },
    {
      "typeId": 3691,
      "name": "Synthetic Oil",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9446.82
    },
    {
      "typeId": 2319,
      "name": "Test Cultures",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9030.71
    },
    {
      "typeId": 2393,
      "name": "Bacteria",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 421.45
    },
    {
      "typeId": 2396,
      "name": "Biofuels",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 226.01
    },
    {
      "typeId": 2390,
      "name": "Electrolytes",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 585.08
    },
    {
      "typeId": 2397,
      "name": "Industrial Fibers",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 786.91
    },
    {
      "typeId": 2392,
      "name": "Oxidizing Compound",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 684.47
    },
    {
      "typeId": 2389,
      "name": "Plasmoids",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 503.37
    },
    {
      "typeId": 2399,
      "name": "Precious Metals",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 582.18
    },
    {
      "typeId": 2395,
      "name": "Proteins",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 779.79
    },
    {
      "typeId": 2398,
      "name": "Reactive Metals",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 410.79
    },
    {
      "typeId": 9828,
      "name": "Silicon",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 790.97
    },
    {
      "typeId": 2400,
      "name": "Toxic Metals",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 315.5
    },
    {
      "typeId": 44,
      "name": "Enriched Uranium",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10856.09
    },
    {
      "typeId": 3683,
      "name": "Oxygen",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 396.53
    },
    {
      "typeId": 3689,
      "name": "Mechanical Parts",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9813.57
    },
    {
      "typeId": 9832,
      "name": "Coolant",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9640.74
    },
    {
      "typeId": 9848,
      "name": "Robotics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 76942.61
    },
    {
      "typeId": 9830,
      "name": "Rocket Fuel",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10943.91
    },
    {
      "typeId": 9834,
      "name": "Guidance Systems",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 76491.74
    },
    {
      "typeId": 9836,
      "name": "Consumer Electronics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8507.09
    },
    {
      "typeId": 9840,
      "name": "Transmitter",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10306.09
    },
    {
      "typeId": 2312,
      "name": "Supertensile Plastics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 13440.87
    },
    {
      "typeId": 2317,
      "name": "Oxides",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8619.74
    },
    {
      "typeId": 3812,
      "name": "Data Sheets",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 186.95
    },
    {
      "typeId": 25588,
      "name": "Scorched Telemetry Processor",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 1918.56,
      "tier": "Common"
    },
    {
      "typeId": 25589,
      "name": "Malfunctioning Shield Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 350.01,
      "tier": "Common"
    },
    {
      "typeId": 25593,
      "name": "Smashed Trigger Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 8202.05,
      "tier": "Common"
    },
    {
      "typeId": 25595,
      "name": "Alloyed Tritanium Bar",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 2269.03,
      "tier": "Common"
    },
    {
      "typeId": 25596,
      "name": "Broken Drone Transceiver",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 3285.08,
      "tier": "Common"
    },
    {
      "typeId": 25597,
      "name": "Damaged Artificial Neural Network",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 223.06,
      "tier": "Common"
    },
    {
      "typeId": 25598,
      "name": "Tripped Power Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 2555.87,
      "tier": "Common"
    },
    {
      "typeId": 25599,
      "name": "Charred Micro Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 221.95,
      "tier": "Common"
    },
    {
      "typeId": 25590,
      "name": "Contaminated Nanite Compound",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 72929.23,
      "tier": "Uncommon"
    },
    {
      "typeId": 25591,
      "name": "Contaminated Lorentz Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 85230.51,
      "tier": "Uncommon"
    },
    {
      "typeId": 25592,
      "name": "Defective Current Pump",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 11931.28,
      "tier": "Uncommon"
    },
    {
      "typeId": 25594,
      "name": "Tangled Power Conduit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 91866.15,
      "tier": "Uncommon"
    },
    {
      "typeId": 25600,
      "name": "Burned Logic Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 24501.54,
      "tier": "Uncommon"
    },
    {
      "typeId": 25601,
      "name": "Fried Interface Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 2401.03,
      "tier": "Uncommon"
    },
    {
      "typeId": 25602,
      "name": "Thruster Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 10948.72,
      "tier": "Uncommon"
    },
    {
      "typeId": 25603,
      "name": "Melted Capacitor Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 4933.23,
      "tier": "Uncommon"
    },
    {
      "typeId": 25604,
      "name": "Conductive Polymer",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 18997.69,
      "tier": "Uncommon"
    },
    {
      "typeId": 25605,
      "name": "Armor Plates",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 23235.13,
      "tier": "Uncommon"
    },
    {
      "typeId": 25606,
      "name": "Ward Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 13791.28,
      "tier": "Uncommon"
    },
    {
      "typeId": 25607,
      "name": "Telemetry Processor",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 62612.05,
      "tier": "Rare"
    },
    {
      "typeId": 25611,
      "name": "Current Pump",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 51849.23,
      "tier": "Rare"
    },
    {
      "typeId": 25613,
      "name": "Power Conduit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 474171.79,
      "tier": "Rare"
    },
    {
      "typeId": 25614,
      "name": "Single-crystal Superalloy I-beam",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 120520.51,
      "tier": "Rare"
    },
    {
      "typeId": 25615,
      "name": "Drone Transceiver",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 61993.59,
      "tier": "Rare"
    },
    {
      "typeId": 25616,
      "name": "Artificial Neural Network",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 970.49,
      "tier": "Rare"
    },
    {
      "typeId": 25618,
      "name": "Micro Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 3384.46,
      "tier": "Rare"
    },
    {
      "typeId": 25620,
      "name": "Interface Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 7198.59,
      "tier": "Rare"
    },
    {
      "typeId": 25621,
      "name": "Impetus Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 95947.44,
      "tier": "Rare"
    },
    {
      "typeId": 25623,
      "name": "Conductive Thermoplastic",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 21712.82,
      "tier": "Rare"
    },
    {
      "typeId": 25608,
      "name": "Intact Shield Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 453043.59,
      "tier": "Very Rare"
    },
    {
      "typeId": 25609,
      "name": "Nanite Compound",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1224333.33,
      "tier": "Very Rare"
    },
    {
      "typeId": 25610,
      "name": "Lorentz Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 844530.77,
      "tier": "Very Rare"
    },
    {
      "typeId": 25612,
      "name": "Trigger Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1027361.54,
      "tier": "Very Rare"
    },
    {
      "typeId": 25617,
      "name": "Power Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 243253.85,
      "tier": "Very Rare"
    },
    {
      "typeId": 25619,
      "name": "Logic Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1825333.33,
      "tier": "Very Rare"
    },
    {
      "typeId": 25622,
      "name": "Capacitor Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 221994.87,
      "tier": "Very Rare"
    },
    {
      "typeId": 25624,
      "name": "Intact Armor Plates",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 2040641.03,
      "tier": "Very Rare"
    },
    {
      "typeId": 25625,
      "name": "Enhanced Ward Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1155589.74,
      "tier": "Very Rare"
    },
    {
      "typeId": 28361,
      "name": "Drone Synaptic Relay Wiring",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 773.98,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28362,
      "name": "Drone Capillary Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 3940.33,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28363,
      "name": "Drone Cerebral Fragment",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 280761.54,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28364,
      "name": "Drone Tactical Limb",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 4002.92,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28365,
      "name": "Drone Epidermal Shielding Chunk",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 1023.97,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28366,
      "name": "Drone Coronary Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 14972.95,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 21815,
      "name": "Elite Drone AI",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 1921358.97,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 81945,
      "name": "Drone Graviton Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 800820.51,
      "tier": "Rogue Drone"
    }
  ],
  "categories": {
    "minerals": {
      "displayName": "Minerals",
      "visible": true
    },
    "ice_products": {
      "displayName": "Ice Products",
      "visible": true
    },
    "moon_materials": {
      "displayName": "Reaction Materials",
      "visible": true
    },
    "salvaged_materials": {
      "displayName": "Salvaged Materials",
      "visible": true
    }
  },
  "generated": "2026-02-27 15:04 UTC"
};
