// Auto-generated buyback program data
// Generated: 2026-02-26 21:08 UTC
const BUYBACK_DATA = {
  "items": [
    {
      "typeId": 16272,
      "name": "Heavy Water",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 102.47
    },
    {
      "typeId": 16273,
      "name": "Liquid Ozone",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 90,
      "sellRate": 98,
      "accepted": true,
      "quota": 1000000,
      "avgJitaBuy": 90.86
    },
    {
      "typeId": 16275,
      "name": "Strontium Clathrates",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 98,
      "accepted": true,
      "quota": 0,
      "avgJitaBuy": 3256.93
    },
    {
      "typeId": 17887,
      "name": "Oxygen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 740.19
    },
    {
      "typeId": 17889,
      "name": "Hydrogen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 574.03
    },
    {
      "typeId": 16274,
      "name": "Helium Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 841.13
    },
    {
      "typeId": 17888,
      "name": "Nitrogen Isotopes",
      "category": "ice_products",
      "displayCategory": "Ice Products",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 696.46
    },
    {
      "typeId": 34,
      "name": "Tritanium",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 97,
      "accepted": false,
      "quota": 100000000,
      "avgJitaBuy": 3.98
    },
    {
      "typeId": 35,
      "name": "Pyerite",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": false,
      "quota": 20000000,
      "avgJitaBuy": 17.56
    },
    {
      "typeId": 37,
      "name": "Isogen",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 182.06
    },
    {
      "typeId": 36,
      "name": "Mexallon",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 65.04
    },
    {
      "typeId": 38,
      "name": "Nocxium",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": false,
      "quota": 100000,
      "avgJitaBuy": 654.72
    },
    {
      "typeId": 39,
      "name": "Zydrine",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 943.23
    },
    {
      "typeId": 40,
      "name": "Megacyte",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 2474.98
    },
    {
      "typeId": 11399,
      "name": "Morphite",
      "category": "minerals",
      "displayCategory": "Minerals",
      "rate": 95,
      "sellRate": 98,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 18959.13
    },
    {
      "typeId": 16634,
      "name": "Atmospheric Gases",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 231.22
    },
    {
      "typeId": 16635,
      "name": "Evaporite Deposits",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 288.71
    },
    {
      "typeId": 16633,
      "name": "Hydrocarbons",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 97,
      "accepted": true,
      "quota": 100000,
      "avgJitaBuy": 586.57
    },
    {
      "typeId": 16636,
      "name": "Silicates",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 98,
      "sellRate": 97,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 372.28
    },
    {
      "typeId": 16640,
      "name": "Cobalt",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 563.43
    },
    {
      "typeId": 16639,
      "name": "Scandium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": false,
      "quota": 50000,
      "avgJitaBuy": 457.1
    },
    {
      "typeId": 16637,
      "name": "Tungsten",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 1367.2
    },
    {
      "typeId": 16638,
      "name": "Titanium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 98,
      "accepted": true,
      "quota": 50000,
      "avgJitaBuy": 764.29
    },
    {
      "typeId": 16641,
      "name": "Chromium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 5589.43
    },
    {
      "typeId": 16643,
      "name": "Cadmium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 4337.59
    },
    {
      "typeId": 16644,
      "name": "Platinum",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 7265.02
    },
    {
      "typeId": 16642,
      "name": "Vanadium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 99,
      "accepted": true,
      "quota": 25000,
      "avgJitaBuy": 1930.17
    },
    {
      "typeId": 16649,
      "name": "Technetium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": false,
      "quota": 12500,
      "avgJitaBuy": 18757.39
    },
    {
      "typeId": 16646,
      "name": "Mercury",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 3724.61
    },
    {
      "typeId": 16647,
      "name": "Caesium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 5296.93
    },
    {
      "typeId": 16648,
      "name": "Hafnium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 100,
      "accepted": true,
      "quota": 12500,
      "avgJitaBuy": 9072.8
    },
    {
      "typeId": 16652,
      "name": "Promethium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": false,
      "quota": 6250,
      "avgJitaBuy": 61366.3
    },
    {
      "typeId": 16651,
      "name": "Neodymium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": false,
      "quota": 1000,
      "avgJitaBuy": 64675.87
    },
    {
      "typeId": 16650,
      "name": "Dysprosium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": true,
      "quota": 6250,
      "avgJitaBuy": 57021.3
    },
    {
      "typeId": 16653,
      "name": "Thulium",
      "category": "moon_materials",
      "displayCategory": "Reaction Materials",
      "rate": 96,
      "sellRate": 101,
      "accepted": true,
      "quota": 6250,
      "avgJitaBuy": 33537.17
    },
    {
      "typeId": 2329,
      "name": "Biocells",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8569.89
    },
    {
      "typeId": 2345,
      "name": "Camera Drones",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 79846.84
    },
    {
      "typeId": 2348,
      "name": "Gel-Matrix Biopaste",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 113621.05
    },
    {
      "typeId": 2349,
      "name": "Supercomputers",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 88116.32
    },
    {
      "typeId": 2351,
      "name": "Smartfab Units",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 68781.58
    },
    {
      "typeId": 2352,
      "name": "Nuclear Reactors",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 86315.79
    },
    {
      "typeId": 2354,
      "name": "Neocoms",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 81252.11
    },
    {
      "typeId": 2360,
      "name": "Industrial Explosives",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 47412.63
    },
    {
      "typeId": 2361,
      "name": "Hermetic Membranes",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 94841.58
    },
    {
      "typeId": 2367,
      "name": "Cryoprotectant Solution",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 114305.26
    },
    {
      "typeId": 2401,
      "name": "Chiral Structures",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 670.88
    },
    {
      "typeId": 2463,
      "name": "Nanites",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8369.89
    },
    {
      "typeId": 2867,
      "name": "Broadcast Node",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1865210.53
    },
    {
      "typeId": 2868,
      "name": "Integrity Response Drones",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 2097526.32
    },
    {
      "typeId": 2869,
      "name": "Nano-Factory",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 965463.16
    },
    {
      "typeId": 2870,
      "name": "Organic Mortar Applicators",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 905368.42
    },
    {
      "typeId": 2871,
      "name": "Recursive Computing Module",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1189894.74
    },
    {
      "typeId": 2872,
      "name": "Self-Harmonizing Power Core",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1920736.84
    },
    {
      "typeId": 2875,
      "name": "Sterile Conduits",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1027052.63
    },
    {
      "typeId": 2876,
      "name": "Wetware Mainframe",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 1908473.68
    },
    {
      "typeId": 3645,
      "name": "Water",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 448.91
    },
    {
      "typeId": 3775,
      "name": "Viral Agent",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10958.42
    },
    {
      "typeId": 3779,
      "name": "Biomass",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 849.41
    },
    {
      "typeId": 3828,
      "name": "Construction Blocks",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8255.21
    },
    {
      "typeId": 9838,
      "name": "Superconductors",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9740.0
    },
    {
      "typeId": 9842,
      "name": "Miniature Electronics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 11694.21
    },
    {
      "typeId": 9846,
      "name": "Planetary Vehicles",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 113268.42
    },
    {
      "typeId": 2358,
      "name": "Biotech Research Reports",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 86310.71
    },
    {
      "typeId": 2344,
      "name": "Condensates",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 47854.29
    },
    {
      "typeId": 17392,
      "name": "Data Chips",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 88537.86
    },
    {
      "typeId": 2366,
      "name": "Hazmat Detection Systems",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 103100.0
    },
    {
      "typeId": 17898,
      "name": "High-Tech Transmitters",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 84397.14
    },
    {
      "typeId": 2346,
      "name": "Synthetic Synapses",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 80616.43
    },
    {
      "typeId": 12836,
      "name": "Transcranial Microcontrollers",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 68650.71
    },
    {
      "typeId": 17136,
      "name": "Ukomi Superconductors",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 75151.43
    },
    {
      "typeId": 28974,
      "name": "Vaccines",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 70000.0
    },
    {
      "typeId": 15317,
      "name": "Genetically Enhanced Livestock",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 11406.43
    },
    {
      "typeId": 2327,
      "name": "Microfiber Shielding",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 14456.43
    },
    {
      "typeId": 2321,
      "name": "Polyaramids",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 16045.71
    },
    {
      "typeId": 3695,
      "name": "Polytextiles",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 5096.79
    },
    {
      "typeId": 3697,
      "name": "Silicate Glass",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 13097.14
    },
    {
      "typeId": 3691,
      "name": "Synthetic Oil",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9441.71
    },
    {
      "typeId": 2319,
      "name": "Test Cultures",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9085.64
    },
    {
      "typeId": 2393,
      "name": "Bacteria",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 421.01
    },
    {
      "typeId": 2396,
      "name": "Biofuels",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 225.4
    },
    {
      "typeId": 2390,
      "name": "Electrolytes",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 584.77
    },
    {
      "typeId": 2397,
      "name": "Industrial Fibers",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 785.89
    },
    {
      "typeId": 2392,
      "name": "Oxidizing Compound",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 683.23
    },
    {
      "typeId": 2389,
      "name": "Plasmoids",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 502.89
    },
    {
      "typeId": 2399,
      "name": "Precious Metals",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 577.52
    },
    {
      "typeId": 2395,
      "name": "Proteins",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 779.38
    },
    {
      "typeId": 2398,
      "name": "Reactive Metals",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 411.45
    },
    {
      "typeId": 9828,
      "name": "Silicon",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 791.02
    },
    {
      "typeId": 2400,
      "name": "Toxic Metals",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 315.04
    },
    {
      "typeId": 44,
      "name": "Enriched Uranium",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10743.5
    },
    {
      "typeId": 3683,
      "name": "Oxygen",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 395.67
    },
    {
      "typeId": 3689,
      "name": "Mechanical Parts",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9843.5
    },
    {
      "typeId": 9832,
      "name": "Coolant",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 9606.15
    },
    {
      "typeId": 9848,
      "name": "Robotics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 77199.0
    },
    {
      "typeId": 9830,
      "name": "Rocket Fuel",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10928.5
    },
    {
      "typeId": 9834,
      "name": "Guidance Systems",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 76444.5
    },
    {
      "typeId": 9836,
      "name": "Consumer Electronics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8475.8
    },
    {
      "typeId": 9840,
      "name": "Transmitter",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 10322.5
    },
    {
      "typeId": 2312,
      "name": "Supertensile Plastics",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 13403.0
    },
    {
      "typeId": 2317,
      "name": "Oxides",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 8609.3
    },
    {
      "typeId": 3812,
      "name": "Data Sheets",
      "category": "pi_materials",
      "displayCategory": "pi_materials",
      "rate": 98,
      "sellRate": 98,
      "accepted": false,
      "quota": 0,
      "avgJitaBuy": 189.13
    },
    {
      "typeId": 25588,
      "name": "Scorched Telemetry Processor",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 1930.82,
      "tier": "Common"
    },
    {
      "typeId": 25589,
      "name": "Malfunctioning Shield Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 349.77,
      "tier": "Common"
    },
    {
      "typeId": 25593,
      "name": "Smashed Trigger Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 8219.26,
      "tier": "Common"
    },
    {
      "typeId": 25595,
      "name": "Alloyed Tritanium Bar",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 2269.56,
      "tier": "Common"
    },
    {
      "typeId": 25596,
      "name": "Broken Drone Transceiver",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 3235.87,
      "tier": "Common"
    },
    {
      "typeId": 25597,
      "name": "Damaged Artificial Neural Network",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 221.9,
      "tier": "Common"
    },
    {
      "typeId": 25598,
      "name": "Tripped Power Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 2553.36,
      "tier": "Common"
    },
    {
      "typeId": 25599,
      "name": "Charred Micro Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 5000,
      "avgJitaBuy": 220.89,
      "tier": "Common"
    },
    {
      "typeId": 25590,
      "name": "Contaminated Nanite Compound",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 72264.1,
      "tier": "Uncommon"
    },
    {
      "typeId": 25591,
      "name": "Contaminated Lorentz Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 84794.87,
      "tier": "Uncommon"
    },
    {
      "typeId": 25592,
      "name": "Defective Current Pump",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 11826.41,
      "tier": "Uncommon"
    },
    {
      "typeId": 25594,
      "name": "Tangled Power Conduit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 90675.38,
      "tier": "Uncommon"
    },
    {
      "typeId": 25600,
      "name": "Burned Logic Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 24590.77,
      "tier": "Uncommon"
    },
    {
      "typeId": 25601,
      "name": "Fried Interface Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 2383.95,
      "tier": "Uncommon"
    },
    {
      "typeId": 25602,
      "name": "Thruster Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 10990.26,
      "tier": "Uncommon"
    },
    {
      "typeId": 25603,
      "name": "Melted Capacitor Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 4924.0,
      "tier": "Uncommon"
    },
    {
      "typeId": 25604,
      "name": "Conductive Polymer",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 18956.41,
      "tier": "Uncommon"
    },
    {
      "typeId": 25605,
      "name": "Armor Plates",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 23165.64,
      "tier": "Uncommon"
    },
    {
      "typeId": 25606,
      "name": "Ward Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 1000,
      "avgJitaBuy": 13922.82,
      "tier": "Uncommon"
    },
    {
      "typeId": 25607,
      "name": "Telemetry Processor",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 63780.0,
      "tier": "Rare"
    },
    {
      "typeId": 25611,
      "name": "Current Pump",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 51568.21,
      "tier": "Rare"
    },
    {
      "typeId": 25613,
      "name": "Power Conduit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 469658.97,
      "tier": "Rare"
    },
    {
      "typeId": 25614,
      "name": "Single-crystal Superalloy I-beam",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 121471.79,
      "tier": "Rare"
    },
    {
      "typeId": 25615,
      "name": "Drone Transceiver",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 62149.74,
      "tier": "Rare"
    },
    {
      "typeId": 25616,
      "name": "Artificial Neural Network",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 983.01,
      "tier": "Rare"
    },
    {
      "typeId": 25618,
      "name": "Micro Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 3476.74,
      "tier": "Rare"
    },
    {
      "typeId": 25620,
      "name": "Interface Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 7207.51,
      "tier": "Rare"
    },
    {
      "typeId": 25621,
      "name": "Impetus Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 95793.59,
      "tier": "Rare"
    },
    {
      "typeId": 25623,
      "name": "Conductive Thermoplastic",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 500,
      "avgJitaBuy": 21711.28,
      "tier": "Rare"
    },
    {
      "typeId": 25608,
      "name": "Intact Shield Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 456064.1,
      "tier": "Very Rare"
    },
    {
      "typeId": 25609,
      "name": "Nanite Compound",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1229897.44,
      "tier": "Very Rare"
    },
    {
      "typeId": 25610,
      "name": "Lorentz Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 841956.41,
      "tier": "Very Rare"
    },
    {
      "typeId": 25612,
      "name": "Trigger Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1031592.31,
      "tier": "Very Rare"
    },
    {
      "typeId": 25617,
      "name": "Power Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 244594.87,
      "tier": "Very Rare"
    },
    {
      "typeId": 25619,
      "name": "Logic Circuit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1830487.18,
      "tier": "Very Rare"
    },
    {
      "typeId": 25622,
      "name": "Capacitor Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 222479.49,
      "tier": "Very Rare"
    },
    {
      "typeId": 25624,
      "name": "Intact Armor Plates",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 2054051.28,
      "tier": "Very Rare"
    },
    {
      "typeId": 25625,
      "name": "Enhanced Ward Console",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 50,
      "avgJitaBuy": 1166615.38,
      "tier": "Very Rare"
    },
    {
      "typeId": 28361,
      "name": "Drone Synaptic Relay Wiring",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 760.15,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28362,
      "name": "Drone Capillary Fluid",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 3932.72,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28363,
      "name": "Drone Cerebral Fragment",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 282117.95,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28364,
      "name": "Drone Tactical Limb",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 3988.08,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28365,
      "name": "Drone Epidermal Shielding Chunk",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 1016.67,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 28366,
      "name": "Drone Coronary Unit",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 15657.49,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 21815,
      "name": "Elite Drone AI",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 1934923.08,
      "tier": "Rogue Drone"
    },
    {
      "typeId": 81945,
      "name": "Drone Graviton Emitter",
      "category": "salvaged_materials",
      "displayCategory": "Salvaged Materials",
      "rate": 97,
      "sellRate": 101,
      "accepted": true,
      "quota": 250,
      "avgJitaBuy": 800671.79,
      "tier": "Rogue Drone"
    }
  ],
  "categories": {
    "minerals": {
      "displayName": "Minerals",
      "visible": true
    },
    "ice_products": {
      "displayName": "Ice Products",
      "visible": true
    },
    "moon_materials": {
      "displayName": "Reaction Materials",
      "visible": true
    },
    "salvaged_materials": {
      "displayName": "Salvaged Materials",
      "visible": true
    }
  },
  "generated": "2026-02-26 21:08 UTC"
};
